version: 2
updates:
    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: weekly
            day: tuesday
            time: "12:00"
            timezone: America/Chicago