version: 2
updates:

    # Root Level Composer
    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: weekly
            day: tuesday
            time: "12:00"
            timezone: America/Chicago
        reviewers:
            - "EncoreDigitalGroup/dependency-management"